### PR TITLE
feat(client): added gdlint workflow with a default gdlintrc

### LINKED ISSUE #3: Incorporating gdscript toolkit linting check
EDIT: **Linting is throwing an exception, so we will set aside the gdscript toolkit until this issue is fixed**: https://github.com/Scony/godot-gdscript-toolkit/issues/191

As part of our development process, it is important that we maintain clean and consistent code. To help with this, we would like to implement a linter as part of our continuous integration (CI) pipeline. This will ensure that all code changes are checked for syntax errors and style issues before they are merged into the main branch.

- [ ] Enhance current code to pass linting tests
- [ ] Add linting checks as part of our CI pipeline, so that all pull requests are checked for linting errors before they can be merged

https://github.com/Scony/godot-gdscript-toolkit

The linting should allow private function calls outside of its class because it is blocking calls like `super._pressed()` (*private-method-call*)

### PR DESCRIPTION
**Pull request by Dracks**
When finished, this will fix #3 

Status: 
* [X] Added workflow with default configuration
* [x] fixed format of files
* [ ] fixed all lintings

### CODE REVIEW

**Comment by HunterNN** [comment]
@Dracks  See #13

**Comment by Dracks** [comment]
Nice, 

I'm synching right now, I was going to see the plugin in the assets library

**Comment by Dracks** [comment]
> @Dracks See #13 So you don't have to do _fixed format of files_ for all files. I had problems with game.gd, map.gd and unit.gd. Getting there exceptions from gdlint gdformat. Maybe you have more luck with them, but the rest of the gdscripts are already fixed.

I think the problem is the anonymous function with more than one line.

**Comment by Dracks** [comment]
I just saw that they already have an issue (I closed mine): https://github.com/Scony/godot-gdscript-toolkit/issues/191

**Review by HunterNN — APPROVED** [review]

**Pull request merged**
